// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SettingsTest {
  private WebDriver driver;
  private final Init init = new Init();
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private final LoginTest log = new LoginTest();
  @Before
  public void setUp() throws MalformedURLException {


      driver = init.initWebDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test

  public void settings() {
    driver.get("https://www.multitran.com/");


    driver.manage().window().setSize(new Dimension(1132, 800));
    // 3 | mouseOver | xpath=//div[@id='start']/div[3]/div/a |
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'start\']/div[3]/div/a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | xpath=//div[@id='start']/div[3]/div/a |
    driver.findElement(By.xpath("//div[@id=\'start\']/div[3]/div/a")).click();

    // 5 | type | xpath=//div[@id='start']/div[5]/form/table/tbody/tr/td[2]/input | ianstorr
    driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/form/table/tbody/tr/td[2]/input")).sendKeys("ianstorr");
    // 6 | click | xpath=//div[@id='start']/div[5]/form/table |
    driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/form/table")).click();
    // 7 | click | xpath=//div[@id='start']/div[5]/form/table/tbody/tr[2]/td[2]/input |
    driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/form/table/tbody/tr[2]/td[2]/input")).click();
    // 8 | type | xpath=//div[@id='start']/div[5]/form/table/tbody/tr[2]/td[2]/input | sikhus-Jevgu3-xynwot
    driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/form/table/tbody/tr[2]/td[2]/input")).sendKeys("sikhus-Jevgu3-xynwot");
    // 9 | click | xpath=//div[@id='start']/div[5]/form/table/tbody/tr[4]/td/input |
    driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/form/table/tbody/tr[4]/td/input")).click();
    // 10 | mouseOver | xpath=//div[@id='start']/div[5]/table/tbody/tr[3]/td/a |
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/table/tbody/tr[3]/td/a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 11 | mouseOut | xpath=//div[@id='start']/div[5]/table/tbody/tr[3]/td/a |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 12 | mouseOver | xpath=//div[@id='start']/table/tbody/tr/td/a/img |
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'start\']/table/tbody/tr/td/a/img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 13 | mouseOut | xpath=//div[@id='start']/table/tbody/tr/td/a/img |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.manage().window().setSize(new Dimension(1132, 800));
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'start\']/div[3]/div/a[4]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'start\']/div[3]/div/a[4]")).click();
    driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/form/table/tbody/tr[5]/td/input")).click();
    driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/form/table/tbody/tr[6]/td")).click();
    driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/form/table/tbody/tr[6]/td/input")).click();
    driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/form/table/tbody/tr[9]/td/input")).click();
    driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/form/table/tbody/tr[11]/td/input")).click();
    driver.findElement(By.xpath("//div[@id=\'start\']/div[5]/form/table/tbody/tr[18]/td/input")).click();
  }
}
